addons:
# language
language: java

# version numbers
jdk:
    - oraclejdk8

install:
    - pip install coveralls

after_sucess:
  coveralls

# Use JDK 8u45. The above line just causes the use of a minor version of Java 8.
addons:
  apt:
    packages:
      - oracle-java8-installer
